services:
  db:
    image: postgres:latest
    container_name: auth_db
    restart: unless-stopped
    volumes:
      - auth_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=auth 
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=auth
    networks:
      - auth

  auth_backend:
    container_name: auth_backend
    build:
      context: ./auth_backend
    networks:
      - auth
    depends_on:
      - db

  auth_frontend:
    container_name: auth_frontend
    build:
      context: ./auth_frontend
    networks:
      - auth
    depends_on:
      - auth_backend

  caddy:
    container_name: caddy
    build:
      context: ./caddy
    env_file:
      - ./caddy/.env
    restart: unless-stopped
    security_opt:
      - label:disable
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy
      - /etc/localtime:/etc/localtime:ro
    networks:
      - auth


networks:
  auth:

volumes:
  auth_db: