services:
  db:
    image: postgres:latest
    container_name: auth_db
    restart: unless-stopped
    volumes:
      - auth_db:/var/lib/postgresql/data
    env_file:
      - ./postgres/local.env
    networks:
      - auth

  auth_backend:
    container_name: auth_backend
    image: auth_backend:0.0.1
    build:
      context: ./auth_backend
      tags:
        - auth_backend
    networks:
      - auth
    depends_on:
      - db

  auth_frontend:
    container_name: auth_frontend
    image: auth_frontend:0.0.1
    build:
      context: ./auth_frontend
      tags:
        - auth_frontend
    networks:
      - auth
    depends_on:
      - auth_backend

  caddy:
    container_name: caddy
    image: caddy_porkbun:1.0.0
    build:
      context: ./caddy
      tags:
        - caddy_porkbun
    env_file:
      - ./caddy/.env
    restart: unless-stopped
    security_opt:
      - label:disable
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - auth


networks:
  auth:

volumes:
  auth_db:
    name: auth_db